### ISSUE TITLE
Issue with <email@domain> in author

### ISSUE THREAD

**Issue by crownedgrouse** [erldocs/other.erldocs.com#75]
Hi,
By looking at this log,  it appears that xml parsing of author fails when an usual email notation is used:  Name email@domain 
This entry should be escaped with htmlentities or a protected by a CDATA
http://other.erldocs.com/github.com/crownedgrouse/geas/_.txt

**Comment by fenollp** [comment]
Hi @crownedgrouse 

This is OTP's edoc complaining. It seems you have some code in the middle of your documentation and that's something edoc does not like, unless it is braced by `<code>` tags [as explained here](http://erlang.org/pipermail/erlang-questions/2015-January/082444.html)

Please edit [this chunk](https://github.com/crownedgrouse/geas/blob/master/src/geas.erl#L614-L616) and look at [the latest logs](https://raw.githubusercontent.com/erldocs/other.erldocs.com/gh-pages/github.com/crownedgrouse/geas/_.txt) in 24 hours. The daily run should amend your changes.

**Comment by crownedgrouse** [comment]
OK,  I will fix. I thought  the problem was in get_author extraction.
